# Generated by Django 2.2.16 on 2022-07-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220717_1712'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_user_subscribers',
        ),
    ]
